### ISSUE TITLE
node red  Error: listen EACCES: permission denied 0.0.0.0:80

### ISSUE THREAD

**Issue by blue-danube-vienna** [mabunixda/node-red-contrib-alexa-home#112]
Hi!

After update from 1.4.0 to 2.0.0 the message "_node red  Error: listen EACCES: permission denied 0.0.0.0:80_" appears.

I have nginx with  proxy_pass to port 60000 installed. 

iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 60000  does even not work...

is the port 60000  disabled  in 2.0.0 ??

please help
best regards 
blue_danube

**Comment by mabunixda** [comment]
No the port is not disabled, but the default port is set to 80. But of course this should not be overwritten on existing configurations/setups. 
You can also use the proxy method that your nodered installations webserver is used for all communication.

**Comment by GrisuLychen** [comment]
Hi,
sorry i had to push the topic because i can't solve the problem. I get the same error after the update and whatever i write in the port setup, it seams as the plugin use port 80 an node red crashed or was suspended  (runnig as a service or with pi user). I dont want to use root and i did not understand the workaround from blue-danube. Can you help me please. How can i change the port to 60000 or another unprivileged port.

Finaly i also want to say thank you for your great work with the node!

Best Regards
Grisu

**Comment by mabunixda** [comment]
Alexa device need to communicate on port 80. ypu can try to use the proxy flag „use node as webserver“ on the latest version
![Bildschirmfoto 2022-09-19 um 16 49 00](https://user-images.githubusercontent.com/1193145/191046467-2a3cccd0-9682-4901-bce3-f6aa433949e8.png)

here the webserver of nodered is used and no other is started.

**Comment by GrisuLychen** [comment]
Hi mabunixda,
thank you for your advice. Unfortunately it also dosn't work.

Because I didn't know what to do anymore, i read the files of the node and seach for port 80.
And what shoud i say, i dont know why, but i found something and it seams to work.
I change the "80" in /home/pi/.node-red/node_modules/node-red-contrib-alexa-home/alexa/alexa-helper.js to 8980 and restart node red.
In my old setup i prerout the port 80 to 8980 like in the description of the node.

I did not check if alexa find new entries or lights but my homeserver worked for now in the old configuration an my home is a bit smarter again.

**Comment by mabunixda** [comment]
Fine :)  The information about prerouting was also missing on your last post ...
