### ISSUE TITLE
node input?

### ISSUE THREAD

**Issue by tribbles3** [mabunixda/node-red-contrib-alexa-home#28]
I see that the nodes still have inputs but I am unable to get them to work and I don't see any mention of the inputs in any of the documentation anymore. Are they still functional and if so, what are the params?

Thanks.

**Comment by mabunixda** [comment]
Yes you can input params to update the node information in it. This information is displayed also in the alexa app afterwards. 

At the moment you can input as payload objects:
* [brightness](https://github.com/mabunixda/node-red-contrib-alexa-home/blob/master/alexa/alexa-home.js#L85)
* [color](https://github.com/mabunixda/node-red-contrib-alexa-home/blob/master/alexa/alexa-home.js#L79)
* [on/off](https://github.com/mabunixda/node-red-contrib-alexa-home/blob/master/alexa/alexa-home.js#L95)

Normal an input is not routed as output because this would possibly cause endless update loops. But if you want this and know what you are doing, you can set the [output param on the msg](https://github.com/mabunixda/node-red-contrib-alexa-home/blob/master/alexa/alexa-home.js#L133) to let the input passthrough.

**Comment by tribbles3** [comment]
Thanks!

**Comment by tribbles3** [comment]
When using the input I am having trouble getting the msg.payload.on to be output as true.

I send the following to the input:
msg.output = true (boolean)
msg.payload.on = true (boolean)

The output shows msg.payload.on = false

I am sure I am missing something simple here. :)

**Comment by mabunixda** [comment]
@tribbles3  can you retest with version 1.1.0?

**Comment by tribbles3** [comment]
I would be happy to send you a donation so that you can purchase a Gen 3 device. Please let me know if you are interested.

**Comment by mabunixda** [comment]
@tribbles3 i added sponsoring to github project ... you are welcome :)

**Comment by tribbles3** [comment]
Sent. :)
