### ISSUE TITLE
Alexa device malfunction when state change

### ISSUE THREAD

**Issue by hoepps2802** [mabunixda/node-red-contrib-alexa-home#77]
Hello,

As soon as I change the state of the device in the Alexa app or via Alexa speak command , there is an error message that a problem has occurred. in the flow everything is displayed correctly and also switched. 

alexa says: I'm sorry something went wrong

best regards
Matthias

**Comment by Ludacrysis** [comment]
Hi folks,

it seems to me this hasn't been solved so far and I'm experiencing the same problem as hoepps2802.
As  already stated above upon giving alexa a voice command she does her job (apparently) but replies that there has been an error doing so.

One more strange thing about this: If I change the color to pure red it works without error...

best regards

**Comment by mabunixda** [comment]
yeah i assume there is an communication/update problem of the response. Is this only on a certain command? on/off, dimming, ... ?

**Comment by Ludacrysis** [comment]
In my case it only happens for color change (except for pure red). On, Off and Dimming work fine.

**Comment by Ludacrysis** [comment]
I got an idea while doing further testing on this error, correct me if I'm wrong....

Because the hue value is out of range this might cause the mentioned update problem. 
Maybe Alexa is comparing the updated with the requested state and since the hue-value is wrong "she" assumes an error.

This would also explain why this problem isn't occuring for the color red (huevalue: 0) since the huevalue is wrong by a factor (182.04) the 0 isn't affected.

I would like to test it but I couldn't find the section where the response for alexa (and the hue-value) is generated.

**Comment by mabunixda** [comment]
The response is handled in the [alexahub](https://github.com/mabunixda/node-red-contrib-alexa-home/blob/master/alexa/alexa-hub.js#L98). then the implementation is found (here)[https://github.com/mabunixda/node-red-contrib-alexa-home/blob/1649cfe0f0e8f29020d14438b27c3485ccc0663b/alexa/alexa-home-controller.js#L286].

The output data is generated by [generateAPIDevice](https://github.com/mabunixda/node-red-contrib-alexa-home/blob/1649cfe0f0e8f29020d14438b27c3485ccc0663b/alexa/alexa-home-controller.js#L270) function. I must admit the code got quite a mess and must be refactored asap :-( 
Afterwards this data is [rendered](https://github.com/mabunixda/node-red-contrib-alexa-home/blob/1649cfe0f0e8f29020d14438b27c3485ccc0663b/alexa/alexa-home-controller.js#L326) into the json template set-state.json..

**Comment by mabunixda** [comment]
Hopefully the new implementation from #108  and #111  solve these problems
